version: '3.3'
services:
    app:
        restart: on-failure
        build: ./
        ports:
            - '3001:3001'
        #   - "8888:8888"
        volumes:
            - ./src:/usr/src/app/src
            - ./error.log:/usr/src/app/error.log
            - ./mocks:/usr/src/app/mocks
        environment:
            - NODE_ENV=${NODE_ENV}
            - PERSISTENCE_MODE=${PERSISTENCE_MODE}
